IF (OBJECT_ID ('FSOCIETY.sp_get_automoviles') IS NOT NULL)
	DROP PROCEDURE FSOCIETY.sp_get_automoviles
GO


CREATE PROCEDURE FSOCIETY.sp_get_automoviles
AS BEGIN
SELECT
	AUTOS.Patente,
	MODELOS.Description,
	TURNOS.Descripcion,
	PERSONAS.Apellido,
	PERSONAS.Nombre
	FROM FSOCIETY.Autos AUTOS
		LEFT JOIN FSOCIETY.Modelos MODELOS ON AUTOS.IdModelo = MODELOS.Id
		LEFT JOIN FSOCIETY.Turnos TURNOS ON AUTOS.IdTurno = TURNOS.Id
		LEFT JOIN FSOCIETY.Personas PERSONAS ON AUTOS.IdChofer = PERSONAS.Id
END
